### ISSUE TITLE
Csgo (x64) dosnt work after CSGO Update 

### ISSUE THREAD

**Issue by WolverinDEV** [gogobebe2/linux-csgo-external#2]
Hello,
this software dosnt work anymor after the update from today. (http://blog.counter-strike.net/index.php/2016/08/15517/). I hope you can find the new offsets. I think the have moved only a little cup of bytes

**Comment by gogobebe2** [comment]
i dont really play csgo anymore

**Comment by MrWhiteGoat** [comment]
Maybe you can still update it in your free time?
I'm pretty sure it won't take long.

**Comment by WolverinDEV** [comment]
Look at network and the members. There is a responsetory with the working code.
